### ISSUE TITLE
Playing with Chosen - docs enhancement

### ISSUE THREAD

**Issue by CJEdgerton** [formvalidation/support#675]
Chosen select border not changed on `onSuccess` or `onError`. Added the following code to correct that.

CSS: 
```css
.chosen-container.form-control {
    height: inherit; padding: 0px;
}
```
JS: 
```javascript
 $('#chosenForm')
        .find('[name="colors"]')
             .chosen({
                 inherit_select_classes: true
             })
...
```
